### ISSUE TITLE
在kali中运行报错

### ISSUE THREAD

**Issue by MMJ12345** [FeeiCN/ESD#105]
Traceback (most recent call last):
  File "/usr/local/bin/esd", line 33, in <module>
    sys.exit(load_entry_point('ESD==0.0.29', 'console_scripts', 'esd')())
  File "/usr/local/lib/python3.10/dist-packages/ESD-0.0.29-py3.10.egg/ESD/__init__.py", line 905, in main
    esd.run()
  File "/usr/local/lib/python3.10/dist-packages/ESD-0.0.29-py3.10.egg/ESD/__init__.py", line 642, in run
    subs = self.load_sub_domain_dict()
  File "/usr/local/lib/python3.10/dist-packages/ESD-0.0.29-py3.10.egg/ESD/__init__.py", line 332, in load_sub_domain_dict
    with open(path, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/ESD-0.0.29-py3.10.egg/ESD/subs.esd'

**Comment by MMJ12345** [comment]
解决了
