### ISSUE TITLE
win10+python3.8.10 运行报错

### ISSUE THREAD

**Issue by iceriver20002000** [FeeiCN/ESD#106]
2023-01-08 15:48:52,402 [ESD] [INFO] Sub domain dict split 1 and get 1st
2023-01-08 15:48:52,405 [ESD] [INFO] Sub domain dict count: 620328
2023-01-08 15:48:52,406 [ESD] [INFO] Generate coroutines...
2023-01-08 15:48:52,407 [ESD] [INFO] Checking if DNS server 111.xx.xx.xx is available
2023-01-08 15:48:52,407 [ESD] [INFO] Sending message to DNS server a first time
Exception ignored from cffi callback <function _sock_state_cb at 0x000001C8A6A54790>:
Traceback (most recent call last):
  File "c:\python\python38\lib\site-packages\pycares\\__\_init__\__.py", line 99, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "c:\python\python38\lib\site-packages\aiodns\\__\_init__\__.py", line 111, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "c:\python\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError:

**Comment by fuguangChor** [comment]
大哥，弄好了吗
