### ISSUE TITLE
安装出现问题

### ISSUE THREAD

**Issue by helloyw** [FeeiCN/ESD#21]
root@kali:~/ESD# python setup.py 
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    from ESD import __version__
  File "/root/ESD/ESD/__init__.py", line 176
    async def query(self, sub):
            ^
SyntaxError: invalid syntax

root@kali:~/ESD# python3 setup.py 
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    from ESD import __version__
  File "/root/ESD/ESD/__init__.py", line 25, in <module>
    import uvloop
ModuleNotFoundError: No module named 'uvloop'

**Comment by FeeiCN** [comment]
`pip install esd --upgrade`
