### ISSUE TITLE
程序内调用出现如下错误

### ISSUE THREAD

**Issue by niubl** [FeeiCN/ESD#76]
程序内调用方法：
```
from ESD import EnumSubDomain
domains = EnumSubDomain('feei.cn').run()

```

错误提示：
```
Traceback (most recent call last):
  File "webmon.py", line 17, in <module>
    main()
  File "webmon.py", line 13, in main
    domains = EnumSubDomain('feei.cn').run()
  File "/usr/local/lib/python3.6/site-packages/ESD/__init__.py", line 1235, in run
    fofa = FofaEngine(self.fofa_struct, self.conf, self.domain)
  File "/usr/local/lib/python3.6/site-packages/ESD/__init__.py", line 271, in __init__
    self.email = fofa_struct['femail']
KeyError: 'femail'
```

**Comment by ChengWiLL** [comment]
已修复
