### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by winezer0** [FeeiCN/ESD#93]
2020-01-07 07:05:57,616 [ESD] [INFO] Shodan subdomain count: 0
Traceback (most recent call last):
  File "/usr/local/bin/esd", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/ESD/__init__.py", line 13, in main
    esd.run()
  File "/usr/local/lib/python3.7/dist-packages/ESD/engine.py", line 574, in run
    is_success = zoomeye.initialize(base_dir)
  File "/usr/local/lib/python3.7/dist-packages/ESD/lib/thirdpartApi.py", line 113, in initialize
    resp_json = json.loads(resp.text)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kissloo** [comment]
我需要帮助，在kali与centos中遇到这个问题，以前可以正常使用的

**Comment by FeeiCN** [comment]
最新版已修复
