### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by bcdlbgm** [FeeiCN/ESD#94]
![image](https://user-images.githubusercontent.com/45490024/73592842-95fc1700-4539-11ea-9584-fbaf1e5ccc13.png)
`Traceback (most recent call last):
  File "/usr/local/bin/esd", line 11, in <module>
    load_entry_point('ESD==0.0.24', 'console_scripts', 'esd')()
  File "/usr/local/lib/python3.7/dist-packages/ESD-0.0.24-py3.7.egg/ESD/__init__.py", line 1460, in main
    esd.run()
  File "/usr/local/lib/python3.7/dist-packages/ESD-0.0.24-py3.7.egg/ESD/__init__.py", line 1135, in run
    is_all_stable_dns = stable_dns.count(stable_dns[0]) == len(stable_dns)
IndexError: list index out of range
`
报错了老哥。

**Comment by FeeiCN** [comment]
最新版已修复
